// Code generated by goctl. DO NOT EDIT.
package types

type JwtToken struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"` // 建议客户端刷新token的绝对时间
}

type LoginReq struct {
	AuthType   int64  `json:"authType"`
	AuthKey    string `json:"authKey"`
	Captcha    string `json:"captcha,optional"`
	AuthSecret string `json:"authSecret,optional"`
}

type LoginResp struct {
	JwtToken JwtToken `json:"jwtToken"`
}

type RegisterReq struct {
	Mobile  string `json:"mobile"`
	Captcha string `json:"captcha"`
}

type RegisterResp struct {
	JwtToken JwtToken `json:"jwtToken"`
}
