// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gozerobasic/app/gateway/api/v1/captcha/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/captcha/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/captcha/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/captcha/forgetPwd",
				Handler: ForgetPwdHandler(serverCtx),
			},
		},
	)
}
