// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

//go:generate mockgen -destination ./usercenter_mock.go -package usercenterclient -source $GOFILE

package usercenterclient

import (
	"context"

	"gozerobasic/app/services/usercenter/usercenter"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	RegisterResp        = usercenter.RegisterResp
	GetUserByMobileReq  = usercenter.GetUserByMobileReq
	GetUserByMobileResp = usercenter.GetUserByMobileResp
	User                = usercenter.User
	RegisterReq         = usercenter.RegisterReq

	Usercenter interface {
		Register(ctx context.Context, in *RegisterReq) (*RegisterResp, error)
		GetUserByMobile(ctx context.Context, in *GetUserByMobileReq) (*GetUserByMobileResp, error)
	}

	defaultUsercenter struct {
		cli zrpc.Client
	}
)

func NewUsercenter(cli zrpc.Client) Usercenter {
	return &defaultUsercenter{
		cli: cli,
	}
}

func (m *defaultUsercenter) Register(ctx context.Context, in *RegisterReq) (*RegisterResp, error) {
	client := usercenter.NewUsercenterClient(m.cli.Conn())
	return client.Register(ctx, in)
}

func (m *defaultUsercenter) GetUserByMobile(ctx context.Context, in *GetUserByMobileReq) (*GetUserByMobileResp, error) {
	client := usercenter.NewUsercenterClient(m.cli.Conn())
	return client.GetUserByMobile(ctx, in)
}
