// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"gozerobasic/app/services/usercenter/internal/logic"
	"gozerobasic/app/services/usercenter/internal/svc"
	"gozerobasic/app/services/usercenter/usercenter"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Register(ctx context.Context, in *usercenter.RegisterReq) (*usercenter.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GetUserByMobile(ctx context.Context, in *usercenter.GetUserByMobileReq) (*usercenter.GetUserByMobileResp, error) {
	l := logic.NewGetUserByMobileLogic(ctx, s.svcCtx)
	return l.GetUserByMobile(in)
}
