// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package main

import (
	"gozerobasic/lib/interceptor"
	"flag"
	"github.com/tal-tech/go-zero/core/logx"

	"gozerobasic/app/services/usercenter/internal/config"
	"gozerobasic/app/services/usercenter/internal/server"
	"gozerobasic/app/services/usercenter/internal/svc"
	"gozerobasic/app/services/usercenter/usercenter"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)



var configFile = flag.String("f", "etc/usercenter.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)

	ctx := svc.NewServiceContext(c)
	srv := server.NewUsercenterServer(ctx)
	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		usercenter.RegisterUsercenterServer(grpcServer, srv)
	})

	s.AddUnaryInterceptors(interceptor.LoggerInterceptor)

	defer s.Stop()

	logx.Infof("Starting rpc server at %s...", c.ListenOn)
	s.Start()
}
